version: '3.3'
services:
  db:
    image: mysql
    volumes:
      - "./sql-scripts:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: erpcargo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  app:
    image: cargo-app
    ports:
      - 13000:4000